package com.eastcode.server.system.domain;

/**
 * 该类由WANG YIJIN使用Hibernate Tools 3.2.4.GA 生成
 *
 * 生成时间2010-11-8 15:35:45
 */

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import com.eastcode.base.domain.PersistentObject;

/**
 * Station generated by hbm2java
 * 
 * @author WANG YIJIN
 * @version V1.0
 */
@Entity
@Table(name = "STATION")
public class Station implements PersistentObject {

	private static final long serialVersionUID = 1L;

	private BigDecimal id;
	private String code;
	private String name;
	private String type;
	private String status;
	private BigDecimal ownerId;
	private Date createTime;
	private Date updateTime;
	private Set<StationRule> stationRules = new HashSet<StationRule>(0);
	private Set<SystemUserStation> systemUserStations = new HashSet<SystemUserStation>(0);

	@Id
	@GeneratedValue(generator = "ud")
	@GenericGenerator(name = "ud", strategy = "native")
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "OWNER_ID")
	public BigDecimal getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(BigDecimal ownerId) {
		this.ownerId = ownerId;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_TIME")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "UPDATE_TIME")
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@OneToMany
	@Transient
	public Set<StationRule> getStationRules() {
		return this.stationRules;
	}

	public void setStationRules(Set<StationRule> stationRules) {
		this.stationRules = stationRules;
	}

	@OneToMany
	@Transient
	public Set<SystemUserStation> getSystemUserStations() {
		return this.systemUserStations;
	}

	public void setSystemUserStations(Set<SystemUserStation> systemUserStations) {
		this.systemUserStations = systemUserStations;
	}

}
