package com.eastcode.server.system.domain;

/**
 * 该类由WANG YIJIN使用Hibernate Tools 3.2.4.GA 生成
 *
 * 生成时间2010-11-8 15:35:45
 */

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import com.eastcode.base.domain.PersistentObject;

/**
 * SystemMenu generated by hbm2java
 * 
 * @author WANG YIJIN
 * @version V1.0
 */
@Entity
@Table(name = "SYSTEM_MENU")
public class SystemMenu implements PersistentObject {

	private static final long serialVersionUID = 1L;

	private BigDecimal id;
	private String code;
	private String name;
	private String url;
	private String type;
	private String img;
	private BigDecimal parentId;
	private String status;
	private String leaf;
	private String target;
	private Date createTime;
	private Date updateTime;
	private Map<BigDecimal, SystemMenu> childMap = new TreeMap<BigDecimal, SystemMenu>();
	private StringBuffer childBuf = new StringBuffer();

	@Id
	@GeneratedValue(generator = "ud")
	@GenericGenerator(name = "ud", strategy = "native")
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@Column(name = "PARENT_ID")
	public BigDecimal getParentId() {
		return this.parentId;
	}

	public void setParentId(BigDecimal parentId) {
		this.parentId = parentId;
	}

	public String getLeaf() {
		return leaf;
	}

	public void setLeaf(String leaf) {
		this.leaf = leaf;
	}

	public String getTarget() {
		return target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_TIME")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "UPDATE_TIME")
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Transient
	public Map<BigDecimal, SystemMenu> getChildMap() {
		return childMap;
	}

	public void setChildMap(Map<BigDecimal, SystemMenu> childMap) {
		this.childMap = childMap;
	}

	@Transient
	public StringBuffer getChildBuf() {
		return childBuf;
	}

	public void setChildBuf(StringBuffer childBuf) {
		this.childBuf = childBuf;
	}

	/***
	 * 添加叶子节点
	 * 
	 * @param systemMenu
	 */
	public void addChild(SystemMenu systemMenu) {
		childMap.put(systemMenu.getId(), systemMenu);
	}
}
