package com.eastcode.server.system.domain;

/**
 * 该类由WANG YIJIN使用Hibernate Tools 3.2.4.GA 生成
 *
 * 生成时间2010-11-8 15:35:45
 */

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import com.eastcode.base.domain.PersistentObject;

/**
 * SystemUserStation generated by hbm2java
 * 
 * @author WANG YIJIN
 * @version V1.0
 */
@Entity
@Table(name = "SYSTEM_USER_STATION")
public class SystemUserStation implements PersistentObject {

	private static final long serialVersionUID = 1L;

	private BigDecimal id;
	private Station station;
	private SystemUser systemUser;
	private Date createTime;
	private Date updateTime;

	@Id
	@GeneratedValue(generator = "ud")
	@GenericGenerator(name = "ud", strategy = "native")
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@OneToOne
	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	@OneToOne
	@JoinColumn(name = "SYSTEM_USER_ID")
	public SystemUser getSystemUser() {
		return this.systemUser;
	}

	public void setSystemUser(SystemUser systemUser) {
		this.systemUser = systemUser;
	}

	@Column(name = "CREATE_TIME")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "UPDATE_TIME")
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
